pipeline {
  agent none

  stages {
    stage('Back-end') {
      agent {
        docker {
          image 'maven:3.8.1-adoptopenjdk-11'
        }
      }
      steps {
        echo '--- Backend Container ---'
        sh 'mvn --version'
        sh 'echo "Hello from Maven container (Back-end)"'
      }
    }

    stage('Front-end') {
      agent {
        docker {
          image 'node:16-alpine'
        }
      }
      steps {
        echo '--- Frontend Container ---'
        sh 'node --version'
        sh 'echo "Hello from Node container (Front-end)"'
      }
    }
  }
}
